general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = /home/maka/Pictures/wallpaper/vvvv.png
    blur_passes = 3
    blur_size = 6
    brightness = 0.35
}

label {
    monitor =
    text = $TIME
    font_family = Pretendard ExtraBold
    font_size = 96
    color = rgb(ffffff)
    position = 0, 170
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%Y-%m-%d %a"
    font_family = Pretendard SemiBold
    font_size = 18
    color = rgb(888888)
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 44
    outline_thickness = 1
    rounding = 0
    shadow_passes = 0
    outer_color = rgb(444444)
    inner_color = rgb(141414)
    font_color = rgb(ffffff)
    font_family = Pretendard SemiBold
    check_color = rgb(888888)
    fail_color = rgb(a00000)
    capslock_color = rgb(ffaa00)
    placeholder_text = <span foreground="##888888">Password</span>
    fail_text = <span foreground="##ff4444">$FAIL</span>
    dots_size = 0.2
    dots_spacing = 0.4
    dots_rounding = 0
    fade_on_empty = false
    position = 0, -20
    halign = center
    valign = center
}
