general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = false
}

background {
    monitor =
    color = rgb(000000)
}

label {
    monitor =
    text = $TIME
    font_family = Pretendard SemiBold
    font_size = 28
    color = rgb(c4c4c4)
    position = 0, 28
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    font_family = Pretendard SemiBold
    font_size = 13
    color = rgb(666666)
    position = 0, -12
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 220, 40
    outline_thickness = 1
    rounding = 16
    shadow_passes = 0
    outer_color = rgb(888888)
    inner_color = rgb(333333)
    font_color = rgb(c4c4c4)
    font_family = Pretendard SemiBold
    check_color = rgb(aaaaaa)
    fail_color = rgb(ff3117)
    capslock_color = rgb(ffaa00)
    placeholder_text =
    fail_text =
    dots_size = 0.25
    dots_spacing = 0.3
    dots_rounding = -1
    dots_center = true
    fade_on_empty = false
    position = 0, -50
    halign = center
    valign = center
}
